defaults:
  # We cannot use AutoTokenizerFactory for older LLaMA models.
  - override /model/tokenizer_factory@_here_: llama

identifier: llama1_7b
base_model_name_or_path: jeffwan/llama-7b-hf
ctx_length: 2048
