# @package _global_

# Config of ACIP eval entrypoint (see acip.entrypoints.acip_eval).

defaults:
  # Load ACIPEntrypointConf and base config.
  - /acip/ACIPEntrypointConf@_here_
  - base
  # Data-related configs.
  - /data: c4  # dummy (no tuning)
  # Evaluation-related configs.
  - /eval: default
  # Model-related configs.
  - /model/model_factory@model: acip_finetune  # same factory-type as finetune, i.e., loading an existing ACIP model
  - /model/tokenizer_factory@model: default
  - /model/base@model: default  # it's important that base comes after tokenizer_factory because it may overwrite it
  # Training-related configs.
  - /training: base
  - /training/objective@training: acip_finetune  # dummy (no tuning)
  - /training/optimizer@training: acip_finetune  # dummy (no tuning)
  - /training/benchmarking@training:  # will be used as evaluator
      - default
  # Save and load behavior of the ACIP model.
  - storage@acip: acip_eval
  - _self_
  # Experiment and options configs, overwriting parts of this entrypoint.
  - /experiment:
  - /options:

run:
  id: ${run.type}__${model.identifier}__ratio${acip.prune_to_ratio}  # add a suffix in ablation experiments
  group: ${data.identifier}__${model.identifier}__${run.series}  # group by dataset & model
  type: eval
  tags_default:
    - type:${run.type}
    - series:${run.series}
    - model:${model.identifier}
    - data:${data.identifier}
  save:  # do not save the loaded model (again)
    - config
    - results

training:
  trainer:
    max_steps: 0  # prevents tuning so that the model is just evaluated

# Define ACIP-eval-specific config.
acip:
  quantize_weights: false  # optionally quantize U and V weights of SVD parametrization
  # Target size ratio at which the model is materialized after loading.
  # If "test_ratios" is specified, this is ignored and you can leave it None.
  prune_to_ratio:
  measure_ratio_full: false  # count all parameters while compressing (true) or just all parametrized modules (false)
  pruning_config:  # additional options for the pruning process, None means the default config
  compress_and_unparametrize: false  # whether to actually compress the model (cannot be reverted)
  # Size ratios at which to evaluate the final model. None means the ACIP model is evaluated at it is.
  test_ratios: [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  lr: 2e-4  # dummy (no tuning)
